title: NOT
author: DipatswaIII
email: dipaxfaith@gmail.com
description: _life is good for those who believe_
  The best version of yourself is now because you are not who you were yesterday

# social links
twitter_username: Tshwatja
github_username:  DipatswaIII

show_excerpts: true
theme: minima
